package com.inolia_zaicek.wizard_terra_cuiros.Config;

import net.minecraftforge.common.ForgeConfigSpec;

public class WTCConfig {
    public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static final ForgeConfigSpec SPEC;
    //祝福
    public static final ForgeConfigSpec.IntValue TheCommunityKillCount;
    public static final ForgeConfigSpec.IntValue OverMaxACCESSORIES;
    public static final ForgeConfigSpec.ConfigValue<Float> TheCommunityUpNumber;
    public static final ForgeConfigSpec.DoubleValue TrackChance;
    public static final ForgeConfigSpec.DoubleValue DarkFocus;
    public static final ForgeConfigSpec.DoubleValue HauntedFocus;
    public static final ForgeConfigSpec.DoubleValue SoulFoucs;
    public static final ForgeConfigSpec.DoubleValue WarpedFoucs;
    public static final ForgeConfigSpec.DoubleValue GoetyFoucs;
    public static final ForgeConfigSpec.DoubleValue MoonCharmCri;
    public static final ForgeConfigSpec.DoubleValue MoonCharmAtk;
    public static final ForgeConfigSpec.DoubleValue MoonCharmAtkSpeed;
    public static final ForgeConfigSpec.DoubleValue MoonCharmSpeed;
    public static final ForgeConfigSpec.DoubleValue MoonCharmArmor;
    public static final ForgeConfigSpec.DoubleValue MoonCharmRe;
    public static final ForgeConfigSpec.DoubleValue CelestialShellSummon;
    public static final ForgeConfigSpec.DoubleValue DoomEmblemSummon;
    public static final ForgeConfigSpec.DoubleValue UniterEmblemSummon;
    public static final ForgeConfigSpec.DoubleValue CoinLuck;
    public static final ForgeConfigSpec.DoubleValue CoinChance;
    public static final ForgeConfigSpec.DoubleValue GoldRingLuck;
    public static final ForgeConfigSpec.DoubleValue ManaPolarizerMAtk;
    public static final ForgeConfigSpec.DoubleValue ManaPolarizerArs;
    public static final ForgeConfigSpec.DoubleValue ManaPolarizerIron;
    public static final ForgeConfigSpec.DoubleValue ManaPolarizerURe;
    public static final ForgeConfigSpec.DoubleValue ChaosStone;
    public static final ForgeConfigSpec.DoubleValue ChlorophyteQuiverDamage;
    public static final ForgeConfigSpec.DoubleValue ChlorophyteQuiverVelocity;
    public static final ForgeConfigSpec.DoubleValue DeadshotBroochDamage;
    public static final ForgeConfigSpec.DoubleValue DeadshotBroochVelocity;
    public static final ForgeConfigSpec.DoubleValue DeadshotBroochCri;
    public static final ForgeConfigSpec.DoubleValue ElementalQuiverDamage;
    public static final ForgeConfigSpec.DoubleValue ElementalQuiverVelocity;
    public static final ForgeConfigSpec.DoubleValue ElementalQuiverCri;
    public static final ForgeConfigSpec.DoubleValue HerculesBeetle;
    public static final ForgeConfigSpec.DoubleValue NecromanticScroll;
    public static final ForgeConfigSpec.DoubleValue PapyrusScarab;
    public static final ForgeConfigSpec.DoubleValue PygmyNecklace;
    public static final ForgeConfigSpec.DoubleValue SummonerEmblem;
    public static final ForgeConfigSpec.DoubleValue TheCommunityCri;
    public static final ForgeConfigSpec.DoubleValue TheCommunityAtk;
    public static final ForgeConfigSpec.DoubleValue TheCommunityMA;
    public static final ForgeConfigSpec.DoubleValue TheCommunityRa;
    public static final ForgeConfigSpec.DoubleValue TheCommunitySa;
    public static final ForgeConfigSpec.DoubleValue TheCommunityHp;
    public static final ForgeConfigSpec.DoubleValue TheCommunityAr;
    public static final ForgeConfigSpec.DoubleValue TheCommunitySp;
    public static final ForgeConfigSpec.DoubleValue TheCommunityRe;
    public static final ForgeConfigSpec.DoubleValue TheCommunityDr;
    public static final ForgeConfigSpec.DoubleValue MaxAbsorb;
    public static final ForgeConfigSpec.DoubleValue AbsorbMax;
    public static final ForgeConfigSpec.DoubleValue DimensionalSoulArtifactUp;
    public static final ForgeConfigSpec.DoubleValue DimensionalSoulArtifactDown;
    public static final ForgeConfigSpec.DoubleValue SigilOfCalamitasMAtk;
    public static final ForgeConfigSpec.DoubleValue SigilOfCalamitasArsRe;
    public static final ForgeConfigSpec.DoubleValue SigilOfCalamitasIronRe;
    public static final ForgeConfigSpec.DoubleValue SigilOfCalamitasArsMax;
    public static final ForgeConfigSpec.DoubleValue SigilOfCalamitasIronMax;
    public static final ForgeConfigSpec.DoubleValue CelestialEmblem;
    public static final ForgeConfigSpec.DoubleValue CelestialMagnet;

    public static final ForgeConfigSpec.DoubleValue EtherealTalismanMAtk;
    public static final ForgeConfigSpec.DoubleValue EtherealTalismanArsRe;
    public static final ForgeConfigSpec.DoubleValue EtherealTalismanIronRe;
    public static final ForgeConfigSpec.DoubleValue EtherealTalismanArsMax;
    public static final ForgeConfigSpec.DoubleValue EtherealTalismanIronMax;
    public static final ForgeConfigSpec.DoubleValue IronAdd;
    public static final ForgeConfigSpec.DoubleValue IronNumber;
    public static final ForgeConfigSpec.DoubleValue NecklaceOfTheSoulstainedEdge;
    public static final ForgeConfigSpec.DoubleValue NecklaceOfTheDeliveranceEdge;

    public static final ForgeConfigSpec.DoubleValue golden_shower_time;
    public static final ForgeConfigSpec.DoubleValue golden_shower_level;
    public static final ForgeConfigSpec.DoubleValue ichor_arrow_time;
    public static final ForgeConfigSpec.DoubleValue ichor_arrow_level;
    public static final ForgeConfigSpec.DoubleValue flask_of_ichor_time;
    public static final ForgeConfigSpec.DoubleValue flask_of_ichor_level;

    public static final ForgeConfigSpec.DoubleValue assassin_scope_ra;
    public static final ForgeConfigSpec.DoubleValue assassin_scope_cri;
    public static final ForgeConfigSpec.DoubleValue assassin_scope_aggro;
    public static final ForgeConfigSpec.DoubleValue assassin_scope_damage;
    public static final ForgeConfigSpec.DoubleValue assassin_scope_time;

    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_ra;
    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_cri;
    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_aggro;
    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_damage;
    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_time;
    public static final ForgeConfigSpec.DoubleValue rapid_fire_scope_number;

    public static final ForgeConfigSpec.DoubleValue WulfrumBattery;
    public static final ForgeConfigSpec.DoubleValue rover_drive_time;
    public static final ForgeConfigSpec.DoubleValue rover_drive_shield;
    public static final ForgeConfigSpec.DoubleValue rover_drive_armor;
    static {
        //祝福
        BUILDER.push("base");
        rover_drive_armor = BUILDER.comment("钨钢屏障护盾存在时提供的护甲值").defineInRange("rover_shield_armor",10,0F,2147483647);
        rover_drive_shield = BUILDER.comment("钨钢屏障护盾上限").defineInRange("rover_drive_shield",4,0F,2147483647);
        rover_drive_time = BUILDER.comment("钨钢屏障充能时间").defineInRange("rover_shield_time",10,0F,2147483647);
        assassin_scope_ra = BUILDER.comment("暗杀瞄准镜远攻").defineInRange("assassin_scope_ra",0.1,0F,2147483647);
        assassin_scope_cri = BUILDER.comment("暗杀瞄准镜暴击率").defineInRange("assassin_scope_cri",0.1,0F,2147483647);
        assassin_scope_aggro = BUILDER.comment("暗杀瞄准镜减仇恨").defineInRange("assassin_scope_aggro",-400,-10000F,2147483647);
        assassin_scope_damage = BUILDER.comment("暗杀瞄准镜最大增伤").defineInRange("assassin_scope_damage",0.5,0F,2147483647);
        assassin_scope_time = BUILDER.comment("暗杀瞄准镜最长间隔").defineInRange("assassin_scope_time",60,0F,2147483647);

        rapid_fire_scope_ra = BUILDER.comment("速射瞄准镜远攻").defineInRange("rapid_fire_scope_ra",0.1,0F,2147483647);
        rapid_fire_scope_cri = BUILDER.comment("速射瞄准镜暴击率").defineInRange("rapid_fire_scope_cri",0.1,0F,2147483647);
        rapid_fire_scope_aggro = BUILDER.comment("速射瞄准镜减仇恨").defineInRange("rapid_fire_scope_aggro",-400,-10000F,2147483647);
        rapid_fire_scope_damage = BUILDER.comment("速射瞄准镜最大增伤").defineInRange("rapid_fire_scope_damage",0.2,0F,2147483647);
        rapid_fire_scope_time = BUILDER.comment("速射瞄准镜清除增伤间隔时间").defineInRange("rapid_fire_scope_time",100,0F,2147483647);
        rapid_fire_scope_number = BUILDER.comment("速射瞄准镜最大增伤所需次数").defineInRange("rapid_fire_scope_number",10,0F,2147483647);

        EtherealTalismanMAtk = BUILDER.comment("空灵护符魔攻").defineInRange("ethereal_talisman_ma",0.15,0F,2147483647);
        EtherealTalismanArsRe = BUILDER.comment("空灵护符魔源再生").defineInRange("ethereal_talisman_ars_re",0.1,0F,2147483647);
        EtherealTalismanIronRe = BUILDER.comment("空灵护符法力再生").defineInRange("ethereal_talisman_iron_re",0.1,0F,2147483647);
        EtherealTalismanArsMax = BUILDER.comment("空灵护符魔源上限").defineInRange("ethereal_talisman_ars_max",0.3,0F,2147483647);
        EtherealTalismanIronMax = BUILDER.comment("空灵护符法力上限").defineInRange("ethereal_talisman_iron_max",0.3,0F,2147483647);
        IronAdd = BUILDER.comment("法力花系列法力补充比例").defineInRange("iron_mana_add",0.25,0F,2147483647);
        IronNumber = BUILDER.comment("法力花系列法力补充阈值").defineInRange("iron_mana_add",0.5,0F,2147483647);

        CelestialMagnet = BUILDER.comment("天界磁铁范围").defineInRange("celestial_magnet",10.75F,0F,2147483647);
        CelestialEmblem = BUILDER.comment("天界徽章法伤").defineInRange("celestial_emblem",0.15F,0F,2147483647);
        TheCommunityDr = BUILDER.comment("归一石减伤").defineInRange("the_community_dr",0.0025,0F,2147483647);
        TheCommunityRe = BUILDER.comment("归一石回血").defineInRange("the_community_re",0.03,0F,2147483647);
        TheCommunitySp = BUILDER.comment("归一石速度").defineInRange("the_community_speed",0.01,0F,2147483647);
        TheCommunityAr = BUILDER.comment("归一石护甲").defineInRange("the_community_armor",0.5,0F,2147483647);
        TheCommunityHp = BUILDER.comment("归一石血量").defineInRange("the_community_hp",0.005,0F,2147483647);
        TheCommunitySa = BUILDER.comment("归一石召伤").defineInRange("the_community_sa",0.0025,0F,2147483647);
        TheCommunityRa = BUILDER.comment("归一石法伤").defineInRange("the_community_ra",0.005,0F,2147483647);
        TheCommunityMA = BUILDER.comment("归一石法伤").defineInRange("the_community_ma",0.005,0F,2147483647);
        TheCommunityAtk = BUILDER.comment("归一石攻击力").defineInRange("the_community_atk",0.005,0F,2147483647);
        TheCommunityCri = BUILDER.comment("归一石暴击").defineInRange("the_community_cri",0.0025,0F,2147483647);
        HerculesBeetle = BUILDER.comment("甲虫召唤伤害").defineInRange("hercules_beetle",0.075,0F,2147483647);
        NecromanticScroll = BUILDER.comment("死灵卷轴召唤伤害").defineInRange("necromantic_scroll",0.1,0F,2147483647);
        PapyrusScarab = BUILDER.comment("莎草纸召唤伤害").defineInRange("papyrus_scarab",0.125,0F,2147483647);
        PygmyNecklace = BUILDER.comment("矮人项链召唤伤害").defineInRange("pygmy_necklace",0.05,0F,2147483647);
        SummonerEmblem = BUILDER.comment("召唤师徽章").defineInRange("summoner_emblem",0.075,0F,2147483647);
        WulfrumBattery = BUILDER.comment("钨钢电池").defineInRange("summoner_emblem",0.035,0F,2147483647);
        TheCommunityKillCount = BUILDER.comment("最大记入的击杀数").defineInRange("the_community_kill_count",20,0,2147483647);
        OverMaxACCESSORIES = BUILDER.comment("天体洋葱所能提供的最大配饰栏位").defineInRange("over_max_accessories",8,6,100);
        TheCommunityUpNumber = BUILDER.comment("每个击杀数的增长幅度").define("the_community_up_number",1F);
        TrackChance = BUILDER.comment("叶绿箭袋系列弹射物追踪概率").defineInRange("track_chance",0.5F,0F,1F);
        CelestialShellSummon = BUILDER.comment("天界贝壳召唤伤害(其余属性由泰拉饰品本体的天界石配置与月光护身符配置相加得到)").defineInRange("celestial_shell_summon",0.05F,0F,2147483647);
        MoonCharmCri = BUILDER.comment("狼人暴击率").defineInRange("moon_charm_cri",0.02,0F,2147483647);
        MoonCharmAtk = BUILDER.comment("狼人攻击力").defineInRange("moon_charm_atk",0.051,0F,2147483647);
        MoonCharmAtkSpeed = BUILDER.comment("狼人攻速").defineInRange("moon_charm_atk_speed",0.051,0F,2147483647);
        MoonCharmSpeed = BUILDER.comment("狼人移速").defineInRange("moon_charm_speed",0.05,0F,2147483647);
        MoonCharmArmor = BUILDER.comment("狼人护甲").defineInRange("moon_charm_armor",3,0F,2147483647);
        MoonCharmRe = BUILDER.comment("狼人再生").defineInRange("moon_charm_re",0.1,0F,2147483647);
        DoomEmblemSummon = BUILDER.comment("灭绝者召唤伤害").defineInRange("doom_emblem_summon",0.05,0F,2147483647);
        UniterEmblemSummon = BUILDER.comment("联合召唤伤害").defineInRange("uniter_emblem_summon",0.06,0F,2147483647);
        CoinLuck = BUILDER.comment("幸运币幸运值").defineInRange("coin_luck",0.05F,0F,2147483647);
        CoinChance = BUILDER.comment("幸运币爆金币概率").defineInRange("coin_chance",0.1F,0F,2147483647);
        GoldRingLuck = BUILDER.comment("金戒指幸运值").defineInRange("gold_ring_luck",0.2F,0F,2147483647);
        ManaPolarizerMAtk = BUILDER.comment("魔能谐振仪法伤").defineInRange("mana_polarizer_magic_atk",0.06F,0F,2147483647);
        ManaPolarizerArs = BUILDER.comment("魔能谐振仪魔源").defineInRange("mana_polarizer_ars",0.1,0F,2147483647);
        ManaPolarizerIron = BUILDER.comment("魔能谐振仪法力").defineInRange("mana_polarizer_iron",0.1,0F,2147483647);
        ManaPolarizerURe = BUILDER.comment("魔能谐振仪扣血").defineInRange("mana_polarizer_u_re",0.3F,0F,2147483647);
        ChaosStone = BUILDER.comment("混乱石扣血数额").defineInRange("chaos_stone",1.5F,0F,2147483647);
        ChlorophyteQuiverDamage = BUILDER.comment("叶绿箭袋伤害").defineInRange("chlorophyte_quiver_damage",0.1,0F,2147483647);
        ChlorophyteQuiverVelocity = BUILDER.comment("叶绿箭袋加速度").defineInRange("chlorophyte_quiver_speed",0.2,0F,2147483647);
        DeadshotBroochDamage = BUILDER.comment("神射手伤害").defineInRange("deadshot_brooch_damage",0.125,0F,2147483647);
        DeadshotBroochVelocity = BUILDER.comment("神射手加速度").defineInRange("deadshot_brooch_speed",0.2,0F,2147483647);
        DeadshotBroochCri = BUILDER.comment("神射手暴击率").defineInRange("deadshot_brooch_cri",0.05,0F,2147483647);
        ElementalQuiverDamage = BUILDER.comment("元素箭袋伤害").defineInRange("elemental_quiver_damage",0.15,0F,2147483647);
        ElementalQuiverVelocity = BUILDER.comment("元素箭袋加速度").defineInRange("elemental_quiver_speed",0.2,0F,2147483647);
        ElementalQuiverCri = BUILDER.comment("元素箭袋暴击率").defineInRange("elemental_quiver_cri",0.05,0F,2147483647);
        DimensionalSoulArtifactUp = BUILDER.comment("维魂神物增幅").defineInRange("dimensional_soul_artifact_up",0.2,0F,2147483647);
        DimensionalSoulArtifactDown = BUILDER.comment("维魂神物削弱").defineInRange("dimensional_soul_artifact_down",0.15,0F,2147483647);
        SigilOfCalamitasMAtk = BUILDER.comment("灾厄符章魔攻").defineInRange("sigil_of_calamitas_ma",0.15,0F,2147483647);
        SigilOfCalamitasArsRe = BUILDER.comment("灾厄符章魔源再生").defineInRange("sigil_of_calamitas_ars_re",0.1,0F,2147483647);
        SigilOfCalamitasIronRe = BUILDER.comment("灾厄符章法力再生").defineInRange("sigil_of_calamitas_iron_re",0.1,0F,2147483647);
        SigilOfCalamitasArsMax = BUILDER.comment("灾厄符章魔源上限").defineInRange("sigil_of_calamitas_ars_max",0.2,0F,2147483647);
        SigilOfCalamitasIronMax = BUILDER.comment("灾厄符章法力上限").defineInRange("sigil_of_calamitas_iron_max",0.2,0F,2147483647);

        golden_shower_time = BUILDER.comment("黄金雨灵液时间").defineInRange("golden_shower_time",10,0F,2147483647);
        ichor_arrow_time = BUILDER.comment("灵液箭灵液时间").defineInRange("ichor_arrow_time",10,0F,2147483647);
        flask_of_ichor_time = BUILDER.comment("灵液药剂灵液时间").defineInRange("flask_of_ichor_time",10,0F,2147483647);
        golden_shower_level = BUILDER.comment("黄金雨灵液等级").defineInRange("golden_shower_level", 3,0F,2147483647);
        ichor_arrow_level = BUILDER.comment("灵液箭灵液等级").defineInRange("ichor_arrow_level", 3,0F,2147483647);
        flask_of_ichor_level = BUILDER.comment("灵液药剂灵液等级").defineInRange("flask_of_ichor_level", 3,0F,2147483647);
        BUILDER.pop();

        BUILDER.push("goety");
        DarkFocus = BUILDER.comment("黑暗聚晶提升幅度").defineInRange("dark_focus_potency_up",0.5F,0F,2147483647F);
        SoulFoucs = BUILDER.comment("灵魂聚晶提升幅度").defineInRange("soul_focus_potency_up",0.75F,0F,2147483647F);
        WarpedFoucs = BUILDER.comment("诡魂聚晶提升幅度").defineInRange("warped_focus_potency_up",1.25F,0F,2147483647F);
        GoetyFoucs = BUILDER.comment("诡厄聚晶提升幅度").defineInRange("goety_focus_potency_up",1.5F,0F,2147483647F);
        HauntedFocus = BUILDER.comment("缠魂聚晶汲取倍率").defineInRange("haunted_focus_soul_absorb",0.2F,0F,2147483647F);
        MaxAbsorb = BUILDER.comment("汲取上限").defineInRange("max_absorb",0.1F,0F,100);
        AbsorbMax = BUILDER.comment("汲取最大回复上限").defineInRange("absorb_max",0.75F,0F,1);
        BUILDER.pop();

        BUILDER.push("malum");
        NecklaceOfTheSoulstainedEdge = BUILDER.comment("魂染镰刃项链提升数量").defineInRange("necklace_of_the_soulstained_edge",2,0F,2147483647F);
        NecklaceOfTheDeliveranceEdge = BUILDER.comment("挽魂锋镰项链提升数量").defineInRange("necklace_of_the_deliverance_edge",4,0F,2147483647F);
        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}
